trigger:
- staging

variables:
  - group: Deployment Tags
  - name: tag
    value: $[variables['stg-tag']]
  - name: dockerFolderPath
    value: '.'
  - name: dockerEnvironment
    value: 'Stage'
  - name: remoteProjectFolderPath
    value: '/home/rdpuser/projects/mercally-site'
  - name: dockerRegistry
    value: 'northamerica-northeast1-docker.pkg.dev/caramel-primer-419204'
  - name: dockerRepository
    value: 'mercally-site/mercally-site'
  - name: dockerRegistryServiceConnection
    value: 'GoogleArtifactRegistry'
  - name: traefikHost
    value: 'mercally.com'

stages:
- stage: DisplayTagToPublish
  displayName: Tag to be published
  jobs:
  - job: DisplayTag
    steps:
    - script: echo "Docker tag = $(tag)"
      displayName: Confirm Tag Value

- stage: BuildAndPush
  displayName: Build and push Docker image
  dependsOn: DisplayTagToPublish
  jobs:
  - job: BuildAndPushImage
    displayName: Build and push image to registry
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push Docker image to Google Artifact Registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(dockerRegistry)/$(dockerRepository)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(tag)

- stage: Preparation
  displayName: Copy Compose files to VPS
  dependsOn: BuildAndPush
  jobs:
  - job: PushDockerComposeFiles
    displayName: Copy Docker Compose Files
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'mercally.com'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        targetFolder: '$(remoteProjectFolderPath)'
        readyTimeout: '20000'
        failOnEmptySource: true

- stage: Deploy
  displayName: Deploy with Docker Compose on VPS
  dependsOn: Preparation
  jobs:
  - deployment: DockerCompose
    displayName: Deploy Remote
    environment:
      name: Stage
      resourceName: vmi2574441
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Docker tag = $(tag)"
            displayName: Confirm Tag Value

          - task: SSH@0
            displayName: Set TAG and registry in remote .env
            inputs:
              sshEndpoint: 'mercally.com'
              runOptions: 'commands'
              commands: |
                sudo bash -lc 'cat > $(remoteProjectFolderPath)/.env <<EOF
                TAG=$(tag)
                DOCKER_REGISTRY=$(dockerRegistry)
                DOCKER_REPOSITORY=$(dockerRepository)
                AZURE_KV_CLIENT_ID=$(AZURE_KV_CLIENT_ID)
                AZURE_KV_TENANT_ID=$(AZURE_KV_TENANT_ID)
                AZURE_KV_SECRET_ID=$(AZURE_KV_SECRET_ID)
                EOF'
                sudo chmod 444 $(remoteProjectFolderPath)/.env

          - task: SSH@0
            displayName: Run Docker Compose
            inputs:
              sshEndpoint: 'mercally.com'
              runOptions: 'commands'
              commands: |
                docker-compose -f '$(remoteProjectFolderPath)/docker-compose.yml' -f '$(remoteProjectFolderPath)/docker-compose.override.yml' stop
                docker-compose -f '$(remoteProjectFolderPath)/docker-compose.yml' -f '$(remoteProjectFolderPath)/docker-compose.override.yml' rm -f
                docker-compose -f '$(remoteProjectFolderPath)/docker-compose.yml' -f '$(remoteProjectFolderPath)/docker-compose.override.yml' pull
                docker-compose -f '$(remoteProjectFolderPath)/docker-compose.yml' -f '$(remoteProjectFolderPath)/docker-compose.override.yml' up -d
              interactiveSession: true
              readyTimeout: '20000'
